### ISSUE TITLE
Documentation tweak for kubernetes install

### ISSUE THREAD

**Issue by rwillmer** [brightbox/kubernetes-cluster#19]
```ssh ubuntu@$(terraform output master)``` does not work with Terraform 1.5.7.

This used to work, so my guess is that the terraform command has changed over the years; it now surrounds the output with quotes.

This works instead
```ssh ubuntu@$(terraform output --raw master)```

**Comment by rwillmer** [comment]
This is relevant to these pages:
- https://www.brightbox.com/docs/guides/kubernetes/deploy-kubernetes-on-brightbox-cloud/
- https://www.brightbox.com/docs/guides/kubernetes/load-balancers-with-kubernetes/

**Comment by NeilW** [comment]
Thank you.

I've updated the guides on the website to use the '-raw' flag.
